Repository spongedsc/pathways, pull requests merged in 2024-05, with the labels that each got.

#54 [v1] Implement Zustand to fix history states
  bun.lockb
  index.js
  package.json
Labels: enhancement

#58 [v2/feat] Image generation command
  src/commands/imagine.js
Labels: enhancement

#59 [v2/refactor] Move interactionCreate to dedicated file/module, add Actions (context menu) support
  src/actions/index.js
  src/events/interactionCreate.js
  src/index.js
  src/util/deploy.js
  src/util/registerEvents.js
Labels: enhancement

#60 [v2/refactor] General chat improvements & code cleanup
  package.json
  src/actions/readback.js
  src/commands/forget.js
  src/commands/imagine.js
  src/events/messageCreate.js
  src/index.js
  src/util/deploy/cli.js
  src/util/deploy/lib.js
  src/util/models/constants.js
  src/util/models/index.js
  src/util/models/interactions.js
Labels: bug, enhancement, help wanted, missing-v2

#65 [v2/bug] Addressing context overloads
  src/util/models/interactions.js
Labels: bug

#70 [ci] Release tool (ci:release)
  .env.example
  .release-it.cjs
  bun.lockb
  ci/release-it/plugin.js
  package.json
Labels: enhancement

#66 [v2/bug] Handle long responses utilising the Imagine module
  src/util/models/interactions.js
Labels: bug

#75 [feat] Logger
  src/lib/logger.js
Labels: enhancement

#76 [refactor] Recursion & index.js check bypass in structure loader
  src/util/loaders.js
Labels: enhancement

#79 Rename from SpongeChat to Pathways
  .all-contributorsrc
  .env.example
  README.md
  ci/release-it/plugin.js
  docker-compose.yml
  package.json
  src/util/models/constants.js
Labels: documentation

#82 [bug] Fix index.js check in structure loader
  src/util/loaders.js
Labels: bug

#89 [bug] Fix broken structure recursion
  src/util/loaders.js
Labels: bug

#92 ✨ Logger: Mock (for CUTS) & some fixes
  src/lib/logger.js
Labels: enhancement
